name: So Yee
title: So Yee | 苏歌
description: This is my blog where I write something.
meta_description: "So Yee"
image: /assets/images/profile.png

markdown: kramdown
highlighter: rouge

baseurl: '/'

logo: false
paginate: 15
permalink: /:title

twitter:
  username: princeliebe
# Details for the RSS feed generator
url:            'soyee36.github.io'
author:         'So Yee'

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
